import Data from './types/data-types';

interface IDataWrapper {
    products: Data;
}

const data: IDataWrapper = {
    products: [
        {
            id: 1,
            description: 'Моцарелла, сыры чеддер и пармезан, фирменный соус альфредо',
            title: 'Сырная',
            parameters: '30 см, традиционное тесто, 490 г',
            discount: '25%',
            rating: 5.0,
            price: 479,
            brand: 'ДОДО ПИЦЦА',
            category: 'Пицца',
            stock: 15,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/45440e61b26b36d66b22576d7df6cfa7.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/45440e61b26b36d66b22576d7df6cfa7.jpg',
                'https://eda.yandex/images/3583740/367321af494a464492153c720782778a-216x188.jpeg',
            ],
        },
        {
            id: 2,
            description: 'Пикантная пепперони, увеличенная порция моцареллы, фирменный томатный соус',
            title: 'Пеперони',
            parameters: '30 см, традиционное тесто, 580 г',
            discount: '25%',
            rating: 4.1,
            price: 629,
            brand: 'ДОДО ПИЦЦА',
            category: 'Пицца',
            stock: 5,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/Pepperoni-traditional.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/Pepperoni-traditional.jpg',
                'https://eda.yandex/images/3528285/ac9f6be31cb247c1a05489293887d597-216x188.jpeg',
            ],
        },
        {
            id: 3,
            description: 'Ветчина, ананасы, моцарелла, фирменный томатный соус',
            title: 'Гавайская',
            parameters: '30 см, традиционное тесто, 640 г',
            discount: '25%',
            rating: 5.0,
            price: 629,
            brand: 'ДОДО ПИЦЦА',
            category: 'Пицца',
            stock: 10,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/Hawai-traditional.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/Hawai-traditional.jpg',
                'https://eda.yandex/images/3813301/8a9b886d0a974edc98163c3ddbf369d8-216x188.jpeg',
            ],
        },
        {
            id: 4,
            description: 'Острая чоризо, соус барбекю, томаты, красный лук, моцарелла, фирменный томатный соус',
            title: 'Колбаски барбекю',
            parameters: '30 см, традиционное тесто, 490 г',
            discount: '25%',
            rating: 4.45,
            price: 629,
            brand: 'ДОДО ПИЦЦА',
            category: 'Пицца',
            stock: 11,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/Meat-delight-traditional.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/Meat-delight-traditional.jpg',
                'https://eda.yandex/images/3456802/12c6b98c1ffd4ca3ad6c86b68c6fa7ce-216x188.jpeg',
            ],
        },
        {
            id: 5,
            description:
                'Бекон, митболы, пикантная пепперони, моцарелла, томаты, шампиньоны, сладкий перец, красный лук, чеснок, фирменный томатный соус',
            title: 'Додо',
            parameters: '30 см, традиционное тесто, 490 г',
            discount: '25%',
            rating: 4.29,
            price: 719,
            brand: 'ДОДО ПИЦЦА',
            category: 'Пицца',
            stock: 6,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/ce52fafd9a377770c225c26aece12599.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/ce52fafd9a377770c225c26aece12599.jpg',
                'https://eda.yandex/images/3813301/8a9b886d0a974edc98163c3ddbf369d8-216x188.jpeg',
            ],
        },
        {
            id: 6,
            description:
                'Хит ПАПА ДЖОНС с пикантной пепперони, ветчиной, ароматной свининой, фирменным томатным соусом, Моцареллой, шампиньонами, луком, маслинами и сладким перцем. С пикантной остринкой',
            title: 'Супер Папа',
            parameters: '30 см, традиционное тесто, 700 г',
            discount: '12.62%',
            rating: 4.99,
            price: 799,
            brand: 'ПАПА ДЖОНС',
            category: 'Пицца',
            stock: 6,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/ea0010b5eb1c84783a242d11bd014264.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/ea0010b5eb1c84783a242d11bd014264.jpg',
                'https://eda.yandex/images/3529908/8adf44b68f864111b541ffbe16a31e6d-216x188.jpeg',
            ],
        },
        {
            id: 7,
            description:
                'Сочетание сыров: Моцарелла, мягкий молодой сыр, смесь копчёных итальянских сыров, сыр с голубой плесенью, чеддер с соусом пармеджано и орегано',
            title: '9 Сырoв',
            parameters: '30 см, традиционное тесто, 400 г',
            discount: '15%',
            rating: 4.61,
            price: 599,
            brand: 'ПАПА ДЖОНС',
            category: 'Пицца',
            stock: 3,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/d74222636b9758bf63b57bc9432de2e6.jpeg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/d74222636b9758bf63b57bc9432de2e6.jpeg',
                'https://eda.yandex/images/3513074/0a6156296da9493a9e9281faebf25457-216x188.jpeg',
            ],
        },
        {
            id: 8,
            description:
                'Моцарелла, альпийские колбаски, запечённые дольки картофеля, хрустящий бекон, сладкий перец, смесь итальянских сыров и соус барбекю',
            title: 'Баварская',
            parameters: '30 см, традиционное тесто, 380 г',
            discount: '15%',
            rating: 4.89,
            price: 599,
            brand: 'ПАПА ДЖОНС',
            category: 'Пицца',
            stock: 8,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/92bc6bca0b58b92c4bad051716d7af4d.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/92bc6bca0b58b92c4bad051716d7af4d.jpg',
                'https://eda.yandex/images/3667559/abc1f159ac7341c68e9c18e1ae7801f3-216x188.jpeg',
            ],
        },
        {
            id: 9,
            description:
                'Яркий сыр Чеддер, Моцарелла, сочная говядина, сладкий перец и грибы, хрустящий лук, томаты и острый перчик с соусом 1000 островов.',
            title: 'Чеддер Мексикан',
            parameters: '30 см, традиционное тесто, 380 г',
            discount: '15%',
            rating: 4.42,
            price: 899,
            brand: 'ПАПА ДЖОНС',
            category: 'Пицца',
            stock: 4,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/0cbbd6536b44c79e2f1f57680ddebd8e.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/0cbbd6536b44c79e2f1f57680ddebd8e.jpg',
                'https://eda.yandex/images/3813301/8a9b886d0a974edc98163c3ddbf369d8-216x188.jpeg',
            ],
        },
        {
            id: 10,
            description:
                'Оригинальная пицца с говядиной, ароматной ветчиной, двойной порцией хрустящего бекона, соусом Барбекю, Моцареллой, мягким молодым сыром, томатами, жгучим перцем Халапеньо и луком',
            title: 'Большая Бонанза',
            parameters: '30 см, традиционное тесто, 700 г',
            discount: '15%',
            rating: 5.0,
            price: 799,
            brand: 'ПАПА ДЖОНС',
            category: 'Пицца',
            stock: 9,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/full/0908cf630a2876993f41d3233b4f1b16.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/full/0908cf630a2876993f41d3233b4f1b16.jpg',
                'https://eda.yandex/images/3580810/486178011d1149d19606aaa59b0a490a-216x188.jpeg',
            ],
        },
        {
            id: 11,
            description: 'Ветчина, соус чесночный (фирменный), сыр моцарелла, приправа для пиццы.',
            title: 'Мега ветчина',
            parameters: '30 см, традиционное тесто, 530 г',
            discount: '15%',
            rating: 4.69,
            price: 529,
            brand: 'Пицца Сан',
            category: 'Пицца',
            stock: 11,
            thumbnail: 'https://pizzasan.goulash.tech/___/images/menuProduct/6314d3d33c2c8_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/___/images/menuProduct/6314d3d33c2c8_w900_jpg.jpg',
                'https://eda.yandex/images/3454897/5ed7c1d3605c47bfa938f3676cc48808-216x188.jpeg',
            ],
        },
        {
            id: 12,
            description:
                'Фрикадельки, пепперони, перчик халапеньо, сыр моцарелла, томатный соус для пиццы, лук красный, перец болгарский, томаты, соус барбекю, приправа для пиццы.',
            title: 'Сытная с огоньком',
            parameters: '30 см, традиционное тесто, 470 г',
            discount: '35%',
            rating: 4.86,
            price: 659,
            brand: 'Пицца Сан',
            category: 'Пицца',
            stock: 1,
            thumbnail: 'https://pizzasan.goulash.tech/___/images/menuProduct/6314bc07b3b28_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/___/images/menuProduct/6314bc07b3b28_w900_jpg.jpg',
                'https://eda.yandex/images/3456802/12c6b98c1ffd4ca3ad6c86b68c6fa7ce-216x188.jpeg',
            ],
        },
        {
            id: 13,
            description:
                'Фрикадельки, бекон, лук карамелизированный, помидоры, сыр Гауда, соусы Крошка и томатный для пиццы.',
            title: 'Американа',
            parameters: '30 см, традиционное тесто, 770 г',
            discount: '35%',
            rating: 2.25,
            price: 659,
            brand: 'Пицца Сан',
            category: 'Пицца',
            stock: 10,
            thumbnail: 'https://pizzasan.goulash.tech/___/images/menuProduct/630b56b0e2f1e_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/___/images/menuProduct/630b56b0e2f1e_w900_jpg.jpg',
                'https://eda.yandex/images/3518584/2cf9400399b24976887da83c118d8018-216x188.jpeg',
            ],
        },
        {
            id: 14,
            description: 'Фирменный соус жюльен из куриной грудки и шампиньонов под сыром моцарелла.',
            title: 'Жюльен',
            parameters: '30 см, традиционное тесто, 615 г',
            discount: '35%',
            rating: 4.35,
            price: 539,
            brand: 'Пицца Сан',
            category: 'Пицца',
            stock: 8,
            thumbnail: 'https://pizzasan.goulash.tech/__/images/menuProduct/630b57263fa35_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/__/images/menuProduct/630b57263fa35_w900_jpg.jpg',
                'https://eda.yandex/images/2796335/3e4b8544f19249e8a3ca5983d68b5029-216x188.jpeg',
            ],
        },
        {
            id: 15,
            description: 'В составе: курица барбекю, томаты черри, соус манговый, сыр моцарелла, приправа для пиццы.',
            title: 'Тропикана',
            parameters: '30 см, традиционное тесто, 625 г',
            discount: '35%',
            rating: 4.79,
            price: 639,
            brand: 'Пицца Сан',
            category: 'Пицца',
            stock: 4,
            thumbnail: 'https://pizzasan.goulash.tech/___/images/menuProduct/6314c79ad1446_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/___/images/menuProduct/6314c79ad1446_w900_jpg.jpg',
                'https://eda.yandex/images/3813301/8a9b886d0a974edc98163c3ddbf369d8-216x188.jpeg',
            ],
        },
        {
            id: 16,
            description:
                'Томатный соус, моцарелла, томаты, огурцы маринованные, болгарский перец, маслины, сыр фета и соус грин.',
            title: 'Греческая',
            parameters: '30 см, традиционное тесто, 525 г',
            discount: '10%',
            rating: 3.0,
            price: 555,
            brand: 'Точно Пицца',
            category: 'Пицца',
            stock: 7,
            thumbnail: 'https://img.freepik.com/premium-photo/large-pizza-on-a-wooden-table_179755-6990.jpg',
            images: [
                'https://img.freepik.com/premium-photo/large-pizza-on-a-wooden-table_179755-6990.jpg',
                'https://img.freepik.com/premium-photo/large-pizza-on-a-wooden-table-restaurant_179755-6613.jpg',
            ],
        },
        {
            id: 17,
            description: 'Соус с анчоусами и каперсами, моцарелла, шампиньоны и креветки.',
            title: 'Креветки и грибы',
            parameters: '30 см, традиционное тесто, 405 г',
            discount: '10%',
            rating: 4.93,
            price: 555,
            brand: 'Точно Пицца',
            category: 'Пицца',
            stock: 2,
            thumbnail:
                'https://img.freepik.com/premium-photo/seafood-pizza-tomato-shrimp-mediterranean-food_201836-3801.jpg',
            images: [
                'https://img.freepik.com/premium-photo/seafood-pizza-tomato-shrimp-mediterranean-food_201836-3801.jpg',
                'https://img.freepik.com/premium-photo/pizza-with-shrimp-salmon-and-olives_2829-7455.jpg',
            ],
        },
        {
            id: 18,
            description:
                'Томатный соус, моцарелла, бекон, окорок, копчёная куриная грудка, ветчина, грибы, перец болгарский и бальзамический соус.',
            title: 'Точно!',
            parameters: '30 см, традиционное тесто, 620 г',
            discount: '10%',
            rating: 4.44,
            price: 555,
            brand: 'Точно Пицца',
            category: 'Пицца',
            stock: 7,
            thumbnail:
                'https://img.freepik.com/free-photo/front-view-tasty-cheese-pizza-with-red-tomatoes-on-dark-surface_179666-34642.jpg',
            images: [
                'https://img.freepik.com/free-photo/front-view-tasty-cheese-pizza-with-red-tomatoes-on-dark-surface_179666-34642.jpg',
                'https://img.freepik.com/free-photo/vegetarian-pizza-with-zucchini-tomato-peppers-and-mushrooms-on-wooden-table_123827-21927.jpg',
            ],
        },
        {
            id: 19,
            description: 'Томатный соус, моцарелла, томаты, лосось, королевские креветки, маслины и соус дижон.',
            title: 'Морская',
            parameters: '30 см, традиционное тесто, 540 г',
            discount: '10%',
            rating: 4.7,
            price: 1095,
            brand: 'Точно Пицца',
            category: 'Пицца',
            stock: 4,
            thumbnail:
                'https://img.freepik.com/premium-photo/pizza-with-salmon-tomatoes-and-olives-isolated-on-white_290431-2302.jpg',
            images: [
                'https://img.freepik.com/premium-photo/pizza-with-salmon-tomatoes-and-olives-isolated-on-white_290431-2302.jpg',
                'https://img.freepik.com/premium-photo/pizza-with-salmon-tomatoes-and-olives-isolated-on-white_290431-2303.jpgg',
            ],
        },
        {
            id: 20,
            description:
                'Томатный соус, моцарелла, ароматные ветчина и бекон, богарский перец с сочными томатами и рукколой.',
            title: 'Италиан',
            parameters: '30 см, традиционное тесто, 536 г',
            discount: '10%',
            rating: 4.5,
            price: 785,
            brand: 'Точно Пицца',
            category: 'Пицца',
            stock: 10,
            thumbnail:
                'https://img.freepik.com/premium-photo/delicious-pizza-with-salmon-and-vegetables_211786-1881.jpg',
            images: [
                'https://img.freepik.com/premium-photo/delicious-pizza-with-salmon-and-vegetables_211786-1881.jpg',
                'https://eda.yandex/images/3525661/47c25d220bcb4ea982d2c9000a52c2b0-216x188.jpeg',
            ],
        },
        {
            id: 21,
            description:
                'Булка для любителей тьмы, мраморная котлета, овощи, бекон, три сыра, соус гриль и брусничный.',
            title: 'Чернее, чем сердце твоей бывшей',
            parameters: '360 г',
            discount: '23%',
            rating: 5.0,
            price: 470,
            brand: 'КУЛЬТ БУРГЕР',
            category: 'Бургеры',
            stock: 7,
            thumbnail:
                'https://img.freepik.com/free-photo/black-beef-burger-lettuce-tomato-cucumber-cheese-side-view_141793-15447.jpg?t=st=1671864778~exp=1671865378~hmac=6a5fd51b4df4b9504fad44e0eab626c6d02e453b34cdc53993b1a6fb9aad7e0b',
            images: [
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/aed9ce210ca444a547f7fa8be1df6eef.jpg?v1667744315',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A7%D0%B5%D1%80%D0%BD%D1%8B%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 22,
            description:
                'Булка, котлета говяжья, сыр чеддер, салат, помидор, огурец, халапеньо, жареный лук, соус гриль и сырный.',
            title: 'Матадор',
            parameters: '330 г',
            discount: '23%',
            rating: 4.66,
            price: 520,
            brand: 'КУЛЬТ БУРГЕР',
            category: 'Бургеры',
            stock: 2,
            thumbnail:
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/medium/9c5af69ac9ecdb79db4d5a171bed27c1.jpg?v1667750048',
            images: [
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/medium/9c5af69ac9ecdb79db4d5a171bed27c1.jpg?v1667750048',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 23,
            description:
                'Булка белая с кунжутом, говядина, сыр чеддер, Вакамэ, соленый огурец, салат, жареный лук, соусы Zombie и Ореховый.',
            title: 'Водолаз',
            parameters: '380 г',
            discount: '23%',
            rating: 4.13,
            price: 380,
            brand: 'КУЛЬТ БУРГЕР',
            category: 'Бургеры',
            stock: 9,
            thumbnail:
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/8568a4e9d8d2315c2866965f3e2e65f9.jpg?v1667750631',
            images: [
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/8568a4e9d8d2315c2866965f3e2e65f9.jpg?v1667750631',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 24,
            description:
                'Фирменный бургер на черной булке с кунжутом, говядиной, халапеньо, сыром Чеддер, салатом, помидорчиком и огурчиком, также в составе жареный лук и лук, соусы Чесночный и Кетчуп.',
            title: 'Зомби',
            parameters: '360 г',
            discount: '23%',
            rating: 5.0,
            price: 420,
            brand: 'КУЛЬТ БУРГЕР',
            category: 'Бургеры',
            stock: 7,
            thumbnail:
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/9e0c660d4cbbb6b1eb27ecd54322374e.jpg?v1667751100',
            images: [
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/9e0c660d4cbbb6b1eb27ecd54322374e.jpg?v1667751100',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A7%D0%B5%D1%80%D0%BD%D1%8B%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 25,
            description: 'Булка белая с кунжутом, сыр чеддер, салат, помидор, соус Цезарь, кура-кляр.',
            title: 'АвеЦезарь',
            parameters: '350 г',
            discount: '23%',
            rating: 4.59,
            price: 390,
            brand: 'КУЛЬТ БУРГЕР',
            category: 'Бургеры',
            stock: 6,
            thumbnail:
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/4e00c7f0a2b5e41c8e92b572f594bd68.jpg?v1667754206',
            images: [
                'https://ru.foodsoul.pro/uploads/branches/7388/images/items/large/4e00c7f0a2b5e41c8e92b572f594bd68.jpg?v1667754206',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 26,
            description:
                'Биг Маэстро бургер оригинальный – невероятно большой и аппетитный! В нем много сыра, сочных овощей и соуса, тающая во рту булочка и они – нежные и ароматные стрипсы из отборного куриного филе, приготовленного по секретному рецепту с идеальным сочетанием 11 трав и специй. Пробуйте, составу Биг Маэстро бургера оригинального нет равных!',
            title: 'Биг Маэстро Бургер',
            parameters: '281 г',
            discount: '20%',
            rating: 5.0,
            price: 269,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 15,
            thumbnail: 'https://eda.yandex/images/1368744/ebafc3fb228105ed77059a4b4be30de3-400x400nocrop.jpeg',
            images: [
                'https://eda.yandex/images/1368744/ebafc3fb228105ed77059a4b4be30de3-400x400nocrop.jpeg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 27,
            description:
                'Бургер Маэстро Де Люкс оригинальный – изумительное сочетание куриного филе в хрустящей панировке с другими сочными ингредиентами и воздушной булочкой. Какие тут могут быть отзывы – он по-настоящему хорош. Попробуйте сами это идеальное сочетание ингредиентов и наслаждайтесь!',
            title: 'Бургер Маэстро Де Люкс',
            parameters: '227 г',
            discount: '23%',
            rating: 2.5,
            price: 234,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 11,
            thumbnail: 'https://eda.yandex/images/3595513/ac8a3acffa5e11422697ebbd9a24700b-400x400nocrop.jpeg',
            images: [
                'https://eda.yandex/images/3595513/ac8a3acffa5e11422697ebbd9a24700b-400x400nocrop.jpeg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 28,
            description:
                'Еще не пробовали ШефБургер Джуниор? Ваши вкусовые рецепторы он точно порадует! В составе Шефбургера Джуниор под воздушной булочкой скрываются отборные Стрипсы в оригинальной хрустящей панировке, которые готовятся по секретному рецепту  с добавлением трав и специй. Курочка идеально сочетается с сочностью свежих овощей и соусом. Сочный и вкусный Шефбургер Джуниор уже ждет вас в KFC.',
            title: 'Шефбургер Джуниор',
            parameters: '171 г',
            discount: '23%',
            rating: 4.89,
            price: 109,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 5,
            thumbnail: 'https://kfcdostavka24.ru/wp-content/uploads/2020/04/bhfpj1w5yx44kc8c840scwsks80408-600x480.jpg',
            images: [
                'https://kfcdostavka24.ru/wp-content/uploads/2020/04/bhfpj1w5yx44kc8c840scwsks80408-600x480.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 29,
            description:
                'В составе оригинального Шефбургера есть всё, чтобы вкусно и сытно перекусить. Нежная и сочная курица — главный ингредиент. Для приготовления оригинального Шефбургера мы используем отборное куриное филе в оригинальной панировке и секретный рецепт с идеально подобранным сочетанием трав и специй. В Шефбургер оригинальный также добавлена сочность овощей и фирменный соус. И все это на нежной воздушной булочке. Спешите попробовать!',
            title: 'Шефбургер Оригинальный',
            parameters: '190 г',
            discount: '23%',
            rating: 5.0,
            price: 144,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 4,
            thumbnail: 'https://img.freepik.com/premium-photo/burger-with-double-chicken-cutlet_127425-546.jpg?w=1380',
            images: [
                'https://img.freepik.com/premium-photo/burger-with-double-chicken-cutlet_127425-546.jpg?w=1380',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 29,
            description:
                'Осторожно, слишком сырно, сочно и вкусно! Чизбургер Де Люкс — это гораздо больше, чем вы можете себе представить. Ведь главный ингредиент — нежная и сочная курица, вкус которой вы захотите ощутить снова и снова. В её приготовлении у экспертов по курице KFC нет равных. Добавленные овощи и соусы — дополнительное удовольствие. Приготовьтесь, сочность этого бургера зашкаливает!',
            title: 'Чизбургер Де Люкс',
            parameters: '205 г',
            discount: '23%',
            rating: 4.96,
            price: 139,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 9,
            thumbnail: 'https://kfc-kupons.ru/wp-content/uploads/2021/12/chizburger-de-lyuks-kfs.jpg',
            images: [
                'https://kfc-kupons.ru/wp-content/uploads/2021/12/chizburger-de-lyuks-kfs.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 30,
            description:
                'Фантастически большой и неповторимо вкусный! Тройная порция острых куриных стрипсов, двойная порция сыра, гора свежих овощей - на тающей булочке Бриошь, под фирменным соусом, впервые в KFC, специально для тебя. Не пожалеешь!',
            title: 'Биг Маэстро Бургер Острый',
            parameters: '272 г',
            discount: '23%',
            rating: 4.77,
            price: 269,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 1,
            thumbnail:
                'https://img.freepik.com/premium-photo/homemade-beef-burger-delicious-fastfood-closeup_151349-156.jpg',
            images: [
                'https://img.freepik.com/premium-photo/homemade-beef-burger-delicious-fastfood-closeup_151349-156.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 31,
            description:
                'Осторожно, слишком сырно, сочно и вкусно! Чизбургер Де Люкс — это гораздо больше, чем вы можете себе представить. Ведь главный ингредиент — нежная и сочная курица, вкус которой вы захотите ощутить снова и снова. В её приготовлении у экспертов по курице KFC нет равных. Добавленные овощи и соусы — дополнительное удовольствие. Приготовьтесь, сочность этого бургера зашкаливает!',
            title: 'Чизбургер Де Люкс',
            parameters: '205 г',
            discount: '23%',
            rating: 5.0,
            price: 139,
            brand: 'KFC',
            category: 'Бургеры',
            stock: 4,
            thumbnail: 'https://kfc-kupons.ru/wp-content/uploads/2021/12/chizburger-de-lyuks-kfs.jpg',
            images: [
                'https://kfc-kupons.ru/wp-content/uploads/2021/12/chizburger-de-lyuks-kfs.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 32,
            description:
                'В этой новинке всё сырьезно: твёрдый Пармезан, пикантный Блю Чиз, нежная Гауда и плавленный Чеддер объединились с мраморным бифштексом, приготовленным на огне. Это объедение. Это Бургер Кинг!',
            title: 'АНГУС 4 Сыра',
            parameters: '307 г',
            discount: '13%',
            rating: 4.91,
            price: 500,
            brand: 'Burger King',
            category: 'Бургеры',
            stock: 8,
            thumbnail: 'https://eda.yandex/images/3512182/c8016e2833b928f587b68f7935b307c1-216x188.jpeg',
            images: [
                'https://eda.yandex/images/3512182/c8016e2833b928f587b68f7935b307c1-216x188.jpeg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 33,
            description:
                'Премиальная новинка со 100% говядиной Абердин Ангус! Невероятно нежный 150-граммовый мраморный бифштекс на французской булочке бриошь под соусом барбекю и натуральные ингредиенты со всего мира: салат Романо, сыр Гауда, бекон, лук фри и свежие овощи. Стопроцентная мраморная вкуснятина — пробуй срочно!',
            title: 'АНГУС Шеф',
            parameters: '338 г',
            discount: '13%',
            rating: 4.38,
            price: 470,
            brand: 'Burger King',
            category: 'Бургеры',
            stock: 5,
            thumbnail: 'https://eda.yandex/images/3735503/9e368480fb0836af173cfeec98b59974-216x188.jpeg',
            images: [
                'https://eda.yandex/images/3735503/9e368480fb0836af173cfeec98b59974-216x188.jpeg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 34,
            description:
                'Легендарный бургер с бифштексом из 100% говядины на нежной булочке с кунжутом, заправленный сочными помидорами, листовым салатом, майонезом, хрустящими огурчиками и луком.',
            title: 'Воппер',
            parameters: '268 г',
            discount: '13%',
            rating: 4.9,
            price: 260,
            brand: 'Burger King',
            category: 'Бургеры',
            stock: 18,
            thumbnail: 'https://calorizator.ru/sites/default/files/imagecache/product_512/product/triple-whopper.jpg',
            images: [
                'https://calorizator.ru/sites/default/files/imagecache/product_512/product/triple-whopper.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 35,
            description:
                'Легендарный бургер с двумя бифштексами из 100% говядины на нежной булочке с кунжутом, заправленный сочными помидорами, листовым салатом, майонезом, хрустящими огурчиками и луком.',
            title: 'Двойной Воппер',
            parameters: '347 г',
            discount: '13%',
            rating: 5.0,
            price: 350,
            brand: 'Burger King',
            category: 'Бургеры',
            stock: 12,
            thumbnail: 'https://calorizator.ru/sites/default/files/imagecache/product_512/product/triple-whopper.jpg',
            images: [
                'https://calorizator.ru/sites/default/files/imagecache/product_512/product/triple-whopper.jpg',
                'https://lamajo-pizza.ru/images/virtuemart/product/resized/%D0%A1%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%BE%D0%B9%2001_670x670.jpg',
            ],
        },
        {
            id: 36,
            description: 'Идеальное сочетание! Сыры Моцарелла и Чеддер, хрустящий бекон и соус Особый чесночный.',
            title: 'Чеддер палочки с беконом',
            parameters: '360 г',
            discount: '5%',
            rating: 4.5,
            price: 379,
            brand: 'ПАПА ДЖОНС',
            category: 'Закуски',
            stock: 1,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/cart/31733d76f94ac9ecd9f9e7a08544eb1c.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/cart/31733d76f94ac9ecd9f9e7a08544eb1c.jpg',
                'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdRYjS6Qw-YD3DkBcBFiDU2yl_s_kWGVaQNh0CsaFuMGGvL940aAeOmtO6l27MGwqtVac&usqp=CAU',
            ],
        },
        {
            id: 37,
            description:
                'Ролл с куриным филе, томатами, луком, маринованными огурчиками и соусом 1000 островов, сыр Мацарелла.',
            title: 'Джонер Чикен 1000',
            parameters: '170 г',
            discount: '5%',
            rating: 4.45,
            price: 219,
            brand: 'ПАПА ДЖОНС',
            category: 'Закуски',
            stock: 5,
            thumbnail: 'https://www.vkusnyblog.ru/wp-content/uploads/2013/06/roll-iz-lavasha-s-kuricei-i-ovoschami.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/cart/35a589a97d54ddac0c6445e0415595e8.jpg',
                'https://www.vkusnyblog.ru/wp-content/uploads/2013/06/roll-iz-lavasha-s-kuricei-i-ovoschami.jpg',
            ],
        },
        {
            id: 38,
            description:
                'Тортилья пшеничная, сыр Моцарелла, соус Чесночный Ранч, колбаса с/к Чоризо, свежие томаты и шампиньоны.',
            title: 'Чоризо Джонер',
            parameters: '140 г',
            discount: '5%',
            rating: 4.91,
            price: 219,
            brand: 'ПАПА ДЖОНС',
            category: 'Закуски',
            stock: 3,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/cart/52b1a3788776cbf7811edcf38e19e31b.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/cart/52b1a3788776cbf7811edcf38e19e31b.jpg',
                'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0YOy7aC_YuxPjQ1dU6bBixIAqsMtwHIueKw&usqp=CAU',
            ],
        },
        {
            id: 39,
            description: 'Любимая закуска с Моцареллой и соусом Особый чесночный.',
            title: 'Сырные палочки',
            parameters: '280 г',
            discount: '5%',
            rating: 5.0,
            price: 359,
            brand: 'ПАПА ДЖОНС',
            category: 'Закуски',
            stock: 25,
            thumbnail: 'https://cdn.papajohns.ru//images/catalog/thumbs/cart/Cheesesticks.jpg',
            images: [
                'https://cdn.papajohns.ru//images/catalog/thumbs/cart/Cheesesticks.jpg',
                'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdRYjS6Qw-YD3DkBcBFiDU2yl_s_kWGVaQNh0CsaFuMGGvL940aAeOmtO6l27MGwqtVac&usqp=CAU',
            ],
        },
        {
            id: 40,
            description:
                'Рогалики из нежного теста, с чесночным соусом, альпийскими колбасками и сыром моцарелла. Сервируются с соусом на выбор.',
            title: 'Рогалики с колбасками',
            parameters: '180 г',
            discount: '5%',
            rating: 4.13,
            price: 259,
            brand: 'ПАПА ДЖОНС',
            category: 'Закуски',
            stock: 6,
            thumbnail: 'https://eda.yandex.ru/images/1380157/721966fd06fb09245064549ed021441a-680x500.jpg',
            images: [
                'https://eda.yandex.ru/images/1380157/721966fd06fb09245064549ed021441a-680x500.jpg',
                'https://cdn-irec.r-99.com/sites/default/files/imagecache/300o/product-images/590574/SYjy7xsLICFd9z7zw2Mj2A.jpg',
            ],
        },
        {
            id: 41,
            description:
                'Картофель нарезается крупными ломтиками и обжаривается в свежем фритюре. Для приготовления используются лучшие сорта. Хрустящее и сочное блюдо с разными соусами ждет вас!',
            title: 'Баскет Фри',
            parameters: '200 г',
            discount: '18%',
            rating: 5.0,
            price: 149,
            brand: 'KFC',
            category: 'Закуски',
            stock: 2,
            thumbnail:
                'https://img.freepik.com/premium-photo/assorted-flavored-french-fries-with-tomato-sauce-served-in-dish-isolated-on-table-top-view-appetizer_689047-3619.jpg',
            images: [
                'https://img.freepik.com/free-photo/artistic-photo-of-delicious-french-fries_23-2148374861.jpg',
                'https://i0.wp.com/gurmantur.com/wp-content/uploads/2018/06/Belgium-Fries-1.jpg',
            ],
        },
        {
            id: 42,
            description:
                'Картофель нарезается крупными ломтиками и обжаривается в свежем фритюре. Для приготовления используются лучшие сорта. Хрустящее и сочное блюдо с разными соусами ждет вас!',
            title: 'Картофель Фри Стандартный',
            parameters: '100 г',
            discount: '18%',
            rating: 4.98,
            price: 84,
            brand: 'KFC',
            category: 'Закуски',
            stock: 16,
            thumbnail: 'https://img.freepik.com/premium-photo/cone-of-rustic-fries-to-take-away_461960-1874.jpg',
            images: [
                'https://img.freepik.com/premium-photo/cone-of-rustic-fries-to-take-away_461960-1874.jpg',
                'https://img.freepik.com/premium-photo/french-fries-with-sauce_1339-14914.jpg',
            ],
        },
        {
            id: 43,
            description:
                'Маэстро картофель фри от Kfc - это знаменитый картофель фри с хрустящей корочкой в сочетании с ароматным фирменным соусом и хрустящим жареным луком. В составе блюда Маэстро картофель фри она именно такая, какой ее любят во всем мире - рассыпчатая и мягкая внутри, с аппетитной золотистой корочкой. Это безумно вкусно, сытно и питательно.',
            title: 'Маэстро картофель фри',
            parameters: '125 г',
            discount: '18%',
            rating: 4.85,
            price: 159,
            brand: 'KFC',
            category: 'Закуски',
            stock: 21,
            thumbnail:
                'https://cdn-irec.r-99.com/sites/default/files/imagecache/300o/product-images/622549/hoeROcRYmM8cUQMnA6oKA.jpg',
            images: [
                'https://cdn-irec.r-99.com/sites/default/files/imagecache/300o/product-images/622549/hoeROcRYmM8cUQMnA6oKA.jpg',
                'https://vokrugsveta.ua/wp-content/uploads/2017/07/shutterstock_675830416.jpg',
            ],
        },
        {
            id: 44,
            description: 'Горячие дольки нежного сыра с хрустящей корочкой. Идеально с любимым соусом!',
            title: 'Сырные Медальоны (6 шт.)',
            parameters: '72 г',
            discount: '16%',
            rating: 4.35,
            price: 159,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 5,
            thumbnail: 'https://burgerkings.ru/image/cache/catalog/photo/156850992-syrnye-medalony-600x600.jpg',
            images: [
                'https://burgerkings.ru/image/cache/catalog/photo/156850992-syrnye-medalony-600x600.jpg',
                'https://cdn.carte.by/assets/2021/04/08/593fc2a3af19c9db57688adedfe4ac---jpeg_710x_83b40_convert.jpeg',
            ],
        },
        {
            id: 45,
            description:
                'Наши наггетсы сделаны из нежного белого куриного мяса в легкой хрустящей панировке. Рекомендуем к ним восемь разных, но одинаково вкусных соусов на выбор: сырный, кетчуп, барбекю, кисло-сладкий, карри, чесночный, горчичный.',
            title: 'Наггетсы (6 шт.)',
            parameters: '98 г',
            discount: '16%',
            rating: 5.0,
            price: 129,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 16,
            thumbnail: 'https://cookone.ru/wp-content/uploads/2022/02/21f78ee0085945b50fb3a3a67780f423.jpeg',
            images: [
                'https://cookone.ru/wp-content/uploads/2022/02/21f78ee0085945b50fb3a3a67780f423.jpeg',
                'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Chicken_Nuggets.jpg/640px-Chicken_Nuggets.jpg',
            ],
        },
        {
            id: 46,
            description:
                'Золотистые луковые колечки попадают на стол горячими и хрустящими. Рекомендуем с любым из наших соусов.',
            title: 'Луковые Кольца (6 шт.)',
            parameters: '67 г',
            discount: '16%',
            rating: 4.79,
            price: 189,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 10,
            thumbnail: 'https://img.freepik.com/free-photo/fried-rings-with-sweet-chili_140725-3764.jpg',
            images: [
                'https://img.freepik.com/free-photo/fried-rings-with-sweet-chili_140725-3764.jpg',
                'https://img.freepik.com/free-photo/delicious-onion-rings-with-sauce_23-2149235940.jpg',
            ],
        },
        {
            id: 47,
            description:
                'Нежные королевские креветки в легкой хрустящей панировке. Легкая закуска для большой компании с морским настроением. Внимание! Блюдо содержит аллергены – морепродукты.',
            title: 'Креветки (12 шт.)',
            parameters: '192 г',
            discount: '16%',
            rating: 3.5,
            price: 799,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 25,
            thumbnail: 'https://eda.yandex/images/2415806/bb1c7dd5e21500a678519c76cb0b80f8-216x188.jpeg',
            images: [
                'https://eda.yandex/images/2415806/bb1c7dd5e21500a678519c76cb0b80f8-216x188.jpeg',
                'https://foodman.club/wp-content/uploads/2017/11/6517863_ml.jpg',
            ],
        },
        {
            id: 48,
            description:
                'Сочные стрипсы из нежного куриного филе в хрустящей панировке – сплошное куриное удовольствие!',
            title: 'Стрипсы (9 шт.)',
            parameters: '353 г',
            discount: '16%',
            rating: 4.87,
            price: 650,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 15,
            thumbnail: 'https://eda.yandex/images/2415806/bb1c7dd5e21500a678519c76cb0b80f8-216x188.jpeg',
            images: [
                'https://eda.yandex/images/2415806/bb1c7dd5e21500a678519c76cb0b80f8-216x188.jpeg',
                'https://receptisalatov.com/content/recipes/890/main_b_stripsyi-iz-kurinogo-file.jpg',
            ],
        },
        {
            id: 49,
            description: 'Крылышки по фирменному рецепту отлично подойдут как закуска к обеду или пиву.',
            title: 'Крылышки Кинг',
            parameters: '191 г',
            discount: '16%',
            rating: 4.65,
            price: 440,
            brand: 'Burger King',
            category: 'Закуски',
            stock: 7,
            thumbnail: 'https://eda.yandex/images/3790679/985c54c1ad2dfc3542596f318d463d14-216x188.jpeg',
            images: [
                'https://eda.yandex/images/3790679/985c54c1ad2dfc3542596f318d463d14-216x188.jpeg',
                'https://fb.ru/misc/i/thumb/a/1/6/4/5/0/3/9/1645039.jpg',
            ],
        },
        {
            id: 50,
            description:
                'Ванильный шейк — настоящий глоток прохлады. Классический молочный коктейль с ванильным сиропом.',
            title: 'Ванильный Шейк стандартный 0,4л',
            parameters: '0,4 л',
            discount: '30%',
            rating: 5.0,
            price: 150,
            brand: 'Burger King',
            category: 'Напитки',
            stock: 3,
            thumbnail: 'https://eda.yandex/images/1380157/af96172a4134729cf77bd8550c493115-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1380157/af96172a4134729cf77bd8550c493115-216x188.jpeg',
                'https://grandkulinar.ru/uploads/posts/2014-05/1400519099_milkshejk-morozhenogo.jpg',
            ],
        },
        {
            id: 51,
            description:
                'Клубничный шейк — настоящий глоток прохлады. Классический молочный коктейль с клубничным сиропом.',
            title: 'Клубничный Шейк стандартный 0,4л',
            parameters: '0,4 л',
            discount: '30%',
            rating: 5.0,
            price: 150,
            brand: 'Burger King',
            category: 'Напитки',
            stock: 7,
            thumbnail: 'https://eda.yandex/images/1387779/8a6276a51f557293bda0b2a5a339e897-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1387779/8a6276a51f557293bda0b2a5a339e897-216x188.jpeg',
                'https://grandkulinar.ru/uploads/posts/2014-05/1400519099_milkshejk-morozhenogo.jpg',
            ],
        },
        {
            id: 52,
            description:
                'Шоколадный шейк — настоящий глоток прохлады. Классический молочный коктейль с шоколадным сиропом.',
            title: 'Шоколадный Шейк стандартный 0,4л',
            parameters: '0,4 л',
            discount: '30%',
            rating: 5.0,
            price: 150,
            brand: 'Burger King',
            category: 'Напитки',
            stock: 6,
            thumbnail: 'https://eda.yandex/images/1368744/7e1264d7ba3453896bdbcd2878535876-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1368744/7e1264d7ba3453896bdbcd2878535876-216x188.jpeg',
                'https://grandkulinar.ru/uploads/posts/2014-05/1400519099_milkshejk-morozhenogo.jpg',
            ],
        },
        {
            id: 53,
            description:
                'Морс – полезный и сладкий напиток, обогащённый ценными витаминами, утолит жажду и напомнит о самом прекрасном времени года - лете. Полностью натуральный состав и настоящий природный вкус ягод.',
            title: 'Морс Вишня-Мята',
            parameters: '0,45 л',
            discount: '10%',
            rating: 4.9,
            price: 122,
            brand: 'Морсика',
            category: 'Напитки',
            stock: 6,
            thumbnail: 'https://pizzasan.goulash.tech/__/images/menuProduct/639a2f3f07443_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/__/images/menuProduct/639a2f3f07443_w900_jpg.jpg',
                'https://st24.stblizko.ru/images/product/191/360/379_large.jpg',
            ],
        },
        {
            id: 54,
            description:
                'Морс – полезный и сладкий напиток, обогащённый ценными витаминами, утолит жажду и напомнит о самом прекрасном времени года - лете. Полностью натуральный состав и настоящий природный вкус ягод.',
            title: 'Морс Клюква',
            parameters: '0,45 л',
            discount: '10%',
            rating: 5.0,
            price: 122,
            brand: 'Морсика',
            category: 'Напитки',
            stock: 15,
            thumbnail: 'https://pizzasan.goulash.tech/___/images/menuProduct/639a2f1b396d7_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/___/images/menuProduct/639a2f1b396d7_w900_jpg.jpg',
                'https://vepsskiykray.ru/thumb/2/x8iSYU4mzLaKQRGnEPy6kw/800r800/d/klyukva_1.jpg',
            ],
        },
        {
            id: 55,
            description:
                'Морс – полезный и сладкий напиток, обогащённый ценными витаминами, утолит жажду и напомнит о самом прекрасном времени года - лете. Полностью натуральный состав и настоящий природный вкус ягод.',
            title: 'Морс Брусника',
            parameters: '0,45 л',
            discount: '10%',
            rating: 5.0,
            price: 122,
            brand: 'Морсика',
            category: 'Напитки',
            stock: 12,
            thumbnail: 'https://pizzasan.goulash.tech/__/images/menuProduct/639a2efa3dab5_w900_jpg.jpg',
            images: [
                'https://pizzasan.goulash.tech/__/images/menuProduct/639a2efa3dab5_w900_jpg.jpg',
                'https://bahetle-sib.ru/storage/goods/90616_300x300.jpg',
            ],
        },
        {
            id: 56,
            description:
                'Напиток газированный Черноголовка со вкусом эвкалипта, элеутерококка, чёрного чая и кардамона',
            title: 'Байкал 0.5 л',
            parameters: '0,5 л',
            discount: '12%',
            rating: 4.0,
            price: 129,
            brand: 'Черноголовка',
            category: 'Напитки',
            stock: 15,
            thumbnail: 'https://api.magonline.ru/thumbnail/740x494/28/095/28095.jpg',
            images: [
                'https://api.magonline.ru/thumbnail/740x494/28/095/28095.jpg',
                'https://api.magonline.ru/thumbnail/740x494/28/085/28085.jpg',
            ],
        },
        {
            id: 57,
            description: 'Напиток газированный Черноголовка со вкусом медовой груши',
            title: 'Дюшес 0.5 л',
            parameters: '0,5 л',
            discount: '12%',
            rating: 3.5,
            price: 129,
            brand: 'Черноголовка',
            category: 'Напитки',
            stock: 40,
            thumbnail: 'https://api.magonline.ru/thumbnail/simple/28/116/28116.jpg',
            images: [
                'https://api.magonline.ru/thumbnail/simple/28/116/28116.jpg',
                'https://api.magonline.ru/thumbnail/740x494/28/118/28118.jpg',
            ],
        },
        {
            id: 58,
            description: 'Напиток газированный Черноголовка с ароматом свежего эстрагона',
            title: 'Тархун 0.5 л',
            parameters: '0,5 л',
            discount: '12%',
            rating: 3.0,
            price: 129,
            brand: 'Черноголовка',
            category: 'Напитки',
            stock: 35,
            thumbnail: 'https://api.magonline.ru/thumbnail/simple/28/113/28113.jpg',
            images: [
                'https://api.magonline.ru/thumbnail/simple/28/113/28113.jpg',
                'https://api.magonline.ru/thumbnail/740x494/28/115/28115.jpg',
            ],
        },
        {
            id: 59,
            description: '',
            title: 'Кетчуп Томатный',
            parameters: '0,25 г',
            discount: '40%',
            rating: 4.99,
            price: 40,
            brand: 'Heinz',
            category: 'Соусы',
            stock: 50,
            thumbnail: 'https://eda.yandex/images/3512182/bc47c90e9b210dacd8409192104d6317-216x188.jpeg',
            images: [
                'https://eda.yandex/images/3512182/bc47c90e9b210dacd8409192104d6317-216x188.jpeg',
                'https://alania-market.ru/image/cache/catalog/konservy-sousy-pripravy/ketchupy-tomat-sousy/2/34091942-1-640x640.jpg',
            ],
        },
        {
            id: 60,
            description: '',
            title: 'Соус Сырный',
            parameters: '0,25 г',
            discount: '40%',
            rating: 5.0,
            price: 40,
            brand: 'Heinz',
            category: 'Соусы',
            stock: 50,
            thumbnail: 'https://eda.yandex/images/1387779/e472e7d8e4e6d2853b67b2fa2ba75a2a-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1387779/e472e7d8e4e6d2853b67b2fa2ba75a2a-216x188.jpeg',
                'https://menu2go.ru/images/food/423/423_617_20220623143451_8870.jpg',
            ],
        },
        {
            id: 61,
            description: '',
            title: 'Соус Терияки',
            parameters: '0,25 г',
            discount: '40%',
            rating: 4.49,
            price: 40,
            brand: 'Heinz',
            category: 'Соусы',
            stock: 50,
            thumbnail: 'https://eda.yandex/images/1387779/4b04f1a6faa82c90f9f79bfb9ebe164c-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1387779/4b04f1a6faa82c90f9f79bfb9ebe164c-216x188.jpeg',
                'https://i2.stat01.com/1/4672/46718215/afacdb/teriyaki-jpg.jpg',
            ],
        },
        {
            id: 62,
            description: '',
            title: 'Соус Барбекю',
            parameters: '0,25 г',
            discount: '40%',
            rating: 5.0,
            price: 40,
            brand: 'Heinz',
            category: 'Соусы',
            stock: 50,
            thumbnail: 'https://eda.yandex/images/1387779/db6a914e8897efd703a3e034095f9faa-216x188.jpeg',
            images: [
                'https://eda.yandex/images/1387779/db6a914e8897efd703a3e034095f9faa-216x188.jpeg',
                'https://gastrodom24.ru/upload/iblock/847/847123d76bd36f507603c9234532c871.jpeg',
            ],
        },
    ],
};

export default data;
